services:
  gateway-service:
    image: ghcr.io/swagateam/gateway-service:1.0.4
    container_name: taskboard-gateway-serv
    env_file:
      - ./.env
    build:
      context: ../..
      dockerfile: docker/gateway-service/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
      - DOTNET_RUNNING_IN_CONTAINER=true
    restart: always
    ports:
      - 5000:5000
    networks:
      - swaga-network