services:
  project-service:
    container_name: taskboard-project-serv
    build:
      context: .
      dockerfile: docker/project-service/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8082
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
    restart: always
    depends_on:
      project-db:
        condition: service_healthy
    networks:
      - swaga-network
    
  project-db:
    container_name: swaga-project-db
    image: postgres:15-alpine
    env_file:
      - ./.env
    volumes:
      - project-data:/var/lib/postgresql/data
    networks:
      - swaga-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 7s
      timeout: 3s
      retries: 5

networks:
  swaga-network:
