services:
  project-service:
    image: ghcr.io/swagateam/project-service:1.0.4
    container_name: taskboard-project-serv
    env_file:
      - ./.env
    volumes:
      - project-docs-data:/app/docs
      - project-attchs-data:/app/attchs
    build:
      context: ../..
      dockerfile: docker/project-service/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
      - DOTNET_RUNNING_IN_CONTAINER=true
    restart: always
    ports:
      - 5001:5001
    depends_on:
      project-db:
        condition: service_healthy
    networks:
      - swaga-network
    
  project-db:
    container_name: swaga-project-db
    image: postgres:15-alpine
    env_file:
      - ./.env
    volumes:
      - project-data:/var/lib/postgresql/data
    networks:
      - swaga-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USERNAME} -d ${POSTGRES_DB}"]
      interval: 7s
      timeout: 3s
      retries: 5

volumes:
  project-data:
    external: false
  project-docs-data:
  project-attchs-data:
