include:
  - docker/user-service/docker-compose.yml
  - docker/project-service/docker-compose.yml
  - docker/analytics-service/docker-compose.yml
  - docker/gateway-service/docker-compose.yml
  - docker/kafka/docker-compose.yml

networks:
  swaga-network:
    driver: bridge
    name: swaga-network

services:
  db_init:
    image: postgres:15
    depends_on:
      user-db:
        condition: service_healthy
      project-db:
        condition: service_healthy
      analytics-db:
        condition: service_healthy
    environment:
      - POSTGRES_PASSWORD=password"
    volumes:
      - ./migrations/init-fdw.sh:/docker-entrypoint-initdb.d/init-fdw.sh
    networks:
      - swaga-network
    entrypoint: ["docker-entrypoint.sh", "postgres"]