services:
    analytics-service:
    image: ghcr.io/swagateam/analytics-service:1.0.2
    container_name: taskboard-analytics-serv
    env_file:
      - ./.env
    build:
      context: ../..
      dockerfile: docker/analytics-service/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
      - DOTNET_RUNNING_IN_CONTAINER=true
    restart: always
    ports:
      - 5002:5002
    depends_on:
      analytics-db:
        condition: service_healthy
    networks:
      - swaga-network

  analytics-db:
    container_name: swaga-analytics-db
    image: postgres:15-alpine
    env_file:
      - ./.env
    volumes:
      - analytics-data:/var/lib/postgresql/data
    networks:
      - swaga-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USERNAME} -d ${POSTGRES_DB}"]
      interval: 7s
      timeout: 3s
      retries: 5

volumes:
  analytics-data:
    external: false