services:
  analytics-zookeeper:
    container_name: analytics-zookeeper
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "22181:2181"
    networks:
      - swaga-network

  analytics-kafka:
    container_name: analytics-kafka
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=analytics-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "29092:9092"
    depends_on:
      - analytics-zookeeper
    networks:
      - swaga-network
      
  analytics-service:
    container_name: taskboard-analytics-serv
    env_file:
      - ./.env
    build:
      context: ../..
      dockerfile: docker/analytics-service/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
    restart: always
    ports:
      - 5002:5002
    depends_on:
      analytics-db:
        condition: service_healthy
    networks:
      - swaga-network

  analytics-db:
    container_name: swaga-analytics-db
    image: postgres:15-alpine
    env_file:
      - ./.env
    volumes:
      - analytics-data:/var/lib/postgresql/data
    networks:
      - swaga-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USERNAME} -d ${POSTGRES_DB}"]
      interval: 7s
      timeout: 3s
      retries: 5

volumes:
  analytics-data:
    external: false
