version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: multi-db-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: always

volumes:
  pgdata:
