name: deploy

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    name: publish images
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to registry
      run: echo ${{ secrets.PAT }} | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

    - name: Build and push user-service
      run: |
        docker build -t ghcr.io/swagateam/user-service:1.0.3 -f ./docker/user-service/Dockerfile .
        docker push ghcr.io/swagateam/user-service:1.0.4
    
    - name: Build and push gateway-service
      run: |
        docker build -t ghcr.io/swagateam/gateway-service:1.0.5 -f ./docker/gateway-service/Dockerfile .
        docker push ghcr.io/swagateam/gateway-service:1.0.5
    
    - name: Build and push project-service
      run: |
        docker build -t ghcr.io/swagateam/project-service:1.0.4 -f ./docker/project-service/Dockerfile .
        docker push ghcr.io/swagateam/project-service:1.0.4
    
    - name: Build and push analytics-service
      run: |
        docker build -t ghcr.io/swagateam/analytics-service:1.0.3 -f ./docker/analytics-service/Dockerfile .
        docker push ghcr.io/swagateam/analytics-service:1.0.3

  deploy:
        needs: publish
        name: deploy app
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: install ssh keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            echo "${{ secrets.HOST_FINGERPRINT }}" > ~/.ssh/known_hosts
        - name: docker compose update
          run: |
            rsync -avz -e "ssh -i ~/.ssh/id_rsa" docker-compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}
        - name: connect and pull
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker compose pull && docker compose up -d && exit"
        - name: cleanup
          run: rm -rf ~/.ssh
